language: python
python:
  - '3.8'
install:
  - pip install -r requirements.txt
  - python setup.py install --package
script:
  - >
    if [[ "$TRAVIS_BRANCH" =~ ^master$|^[0-9]+\.[0-9]+\.X$ ]]; then
      cd docs
      make clean html EXAMPLES_PATTERN=ex_*
      make doctest
      cd ..
      cp README.rst docs/_build/html
      mv docs/_build/html ./
      git stash
      git checkout "$(git rev-list --max-parents=0 HEAD | tail -n 1)"
      git checkout -b gh-pages
      git config --global user.email "$GH_EMAIL"
      git config --global user.name "$GH_NAME"
      git rm -rf .
      declare -a leftover=("build"
                           "dist"
                           "docs"
                           "*.egg*"
                           "tests")
      for left in "${leftover[@]}"; do
        rm -rf "$left" || echo "$left not present"
      done
      declare -a leftover=(".coverage"
                           "*~"
                           "pip-wheel-metadata"
                           "__pycache__"
                           "*.pyc"
                           "*.pyo"
                           "*.spec")
      for left in "${leftover[@]}"; do
        find . -name "$left" -exec rm -rf {} + || echo "$left not present"
      done
      touch .nojekyll
      mv html/* ./
      rm -r html/
        git add .
        git commit -m "[ci skip] Publish updated documentation"
        git remote rm origin
        git remote add origin https://"$GH_NAME":"$GH_TOKEN"@github.com/"$GH_NAME"/kbtogglr.git
        git push origin gh-pages -f
        git checkout master
      else
        echo "Documentation not for master - pushing skipped"
      fi
  - cd kbtogglr
  - python3 -m pytest --cov=. ../tests
  - coverage xml
after_success:
  - codecov --file coverage.xml --token 487c5247-def1-4604-9224-e0684fc54550
env:
  global:
  - secure: GscJjmG9kJJMlgcXtciXwEFZIR7+CGlrlBoJSIs1vLU6vgVsvPa/rQfqV9DGqvE86PMlaEiGKGUT853aKOBkorpYSf3C1DzWHbcbnGP0NktGEU5lysPZBJ2XKmXvNDH4dUavIbiObpPToY0vxPlzznQ7+UO+FjZ8PrCh85PTKEZk5enB2BOI14sPPoZaScbkl+0XmGq95RdRb07D+01pJ20WgjVOg+6UG+8pwOjxBjCIEH0CN793NS+WKFD2hjqcrUqHobcZ/sIz56YJdk4aNGp/C1MfZaxZCs+qgBK4x+AFq0sW6mH/wL4zi7IPs/tV9MOJ8rDsWegpdBLAsnEiSfvZPF4mD+SQsUxrZHQLuOLR3pUe+V30eH30I8H8poCsW3pr+KwyekUXnOPQy3B0cXPGmUk3APJsZDx96M6KBgrtduwVoy2Zb1b+S1dffeD3sb++OcJnXv9/3U39Rrv5bf8jwD8namHM25utYU059tcJ1cdSuV4ndxeXM7+3VnZghILWX1mKP50jupj6TxczWhk6rdUqxH61ybMCU/iE2RAL3Di8QCKo+o1WLg4ZeiPbEKpJNetESBsolEIqDIwrViXQV96vQ2i1j6Qs1XVeuEEmYLkc/EzGvG+/sda92vDycPE21wQli+RZfk2AP2cMUTf1QfhV5EDx1P7/kc2B/Vw=
  - GH_NAME=jshwi
  - GH_EMAIL=stephen@jshwisolutions.com
