[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 79
exclude = '''
/(
  | \.git
  | \.mypy_cache
  | _build
  | build
  | dist
)/
'''
skip-magic-trailing-comma = true

[tool.coverage.run]
omit = ["whitelist.py", "kbtogglr/__main__.py"]

[tool.coverage.report]
exclude_lines = ['__name__ == "__main__"']
fail_under = 100

[tool.pytest.ini_options]
addopts = [
    "--durations=5",
    "-vv",
    "--color=yes",
    "--cov-report",
    "term-missing",
]
