name: ci

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  ci:
    name: ${{ matrix.os }}-python${{ matrix.python-version }}-node@${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    env:
      PYAUD_GH_NAME: jshwi
      PYAUD_GH_EMAIL: stephen@jshwisolutions.com
      PYAUD_GH_TOKEN: ${{ secrets.PYAUD_GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/kbtogglr

    strategy:
      matrix:
        python-version: [3.8]
        node-version: [16.x.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout build
        id: checkout-build
        uses: actions/checkout@v3

      - name: Install Pipenv
        id: install-pipenv
        run: pipx install pipenv

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pipenv

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Python Packages
        id: install-python-packages
        run: pipenv install --dev

      - name: Install Node Packages
        id: install-node-packages
        run: npm install

      - name: Audit
        id: audit
        run: npm run audit
